version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: apache
    group: apache

hooks:
  AfterInstall:
    - location: scripts/run_java.sh
      timeout: 120
      runas: root